//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shedule_diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaspisanieEntities1 : DbContext
    {

        private static RaspisanieEntities1 _context;

        public RaspisanieEntities1()
            : base("name=RaspisanieEntities1")
        {
        }

        public static RaspisanieEntities1 GetContext()
        {
            if (_context == null)
                _context = new RaspisanieEntities1();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Charts> Charts { get; set; }
        public virtual DbSet<DaysOfWeek> DaysOfWeek { get; set; }
        public virtual DbSet<DaysStatuses> DaysStatuses { get; set; }
        public virtual DbSet<Departaments> Departaments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Shedule> Shedule { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
