//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shedule_diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysOfWeek
    {
        public int ID_dayOfWeek { get; set; }
        public string NameDayOfWeek { get; set; }
        public string AbbreviatureNameDayOfWeek { get; set; }
    }
}
