//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shedule_diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departaments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departaments()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int ID_departament { get; set; }
        public string NameDepartament { get; set; }
        public Nullable<int> ID_DepartamentHead { get; set; }
        public Nullable<decimal> Salary_per_hour_of_work { get; set; }
        public Nullable<int> Hourly_rate { get; set; }
        public Nullable<decimal> Salary_per_hour_of_sick_leave { get; set; }
        public Nullable<int> NDFL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
