//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shedule_diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Shedule = new HashSet<Shedule>();
        }
    
        public int ID_employee { get; set; }
        public string Last_name { get; set; }
        public string Name { get; set; }
        public string Middle_name { get; set; }
        public Nullable<int> ID_departament { get; set; }
        public Nullable<int> ID_chart { get; set; }
        public Nullable<int> ID_status { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
    
        public virtual Departaments Departaments { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shedule> Shedule { get; set; }
    }
}
